{{- if and .Values.rbac.enabled (or (eq .Values.rbac.createServiceAccount nil) .Values.rbac.createServiceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    app: {{ template "allure-testops.fullname" . }}
    chart: {{ template "allure-testops.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.aws.arn }}"
{{- end }}
{{- end -}}
